### Registro do usuário 

POST https://adonis-gaji.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "Andressa",
    "email": "andressas.as1235@gmail.com",
    "password": "12345"
}

### Registro do usuário 

POST https://adonis-gaji.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email": "andressas.as1235@gmail.com",
    "password": "12345"
}

### Mensagem Push

POST https://adonis-gaji.onrender.com/push HTTP/1.1
Content-Type: application/json
Authorization: Bearer Nzc.OicwO-wVhInfi8_suMowajweZ9uuWXvRpM4rpL-UlRZ9ogoOl6B-JIAdi7i5

{
    "id": 1,
    "title": "Olá",
    "body": "Tudo bem?"
}
